### ISSUE TITLE
About RsCrashTest.java 

### ISSUE THREAD

**Issue by AllenFang** [housejester/hbase-debugging#1]
HI @housejester, I've some question about src/main/java/io/d8a/hbase/RsCrashTest.java

I want to know root cause of your region server crash. I think you can find some OOM error on your region server .out file. Why I want to know this issues? Because we have some test for scan a big row, that will cause a java.lang.OutOfMemoryError: Requested array size exceeds VM limit  exception on RegionServer

**Comment by housejester** [comment]
Hi Allen,

Here are the details of our root cause: http://mail-archives.apache.org/mod_mbox/hbase-user/201507.mbox/%3CCAE8tVd%3Dbf4zxrWFOS7Htn291cQAHdWYiSt1%2Bg7qLa8yHeMCuAg%40mail.gmail.com%3E

**Comment by AllenFang** [comment]
Thanks, wow, this post I spend a lot of time to study :). it actually is a Requested array size exceeds VM limit exception and we encounter in these days. However, in HBase 0.94, there's no any Requested array size exceeds VM limit error, but happened in HBase 0.98. so did you think this is a bug in HBase 0.98 and has been solved in HBase 1.1.0 ?

**Comment by housejester** [comment]
There were 2 issues at play really. The "requested array size exceeds vm limit" was happening because it was trying to allocate more buffer than allowed. That would crash the region server. This has just recently been fixed in HBase trunk to NOT crash the server, but result in an error instead. 

However, this was just a bad reaction to a "misbehaving" client call, where the server wasn't handling a large row very well, because the client hasn't indicated that it is ok to return partial rows. The fix (for us) was to set both the batch size AND max result size on scans, allowing the server to return partial row results on scan.next calls (we'd still get the full row, just across multiple calls to scan.next). 

I do think this has been fully solved/fixed in hbase 1.1.0. It seems to also be fixed in 0.98.13 (but for different reasons). Pre 0.98.13, the workaround seems to be to set batch size AND max result size on scans if you have large rows causing this issue. If you're seeing it in post 0.98.13, then it could be a regression, and I wouldn't be too surprised since there was quite a bit of work going on in this area. I'd try setting the batch size AND max result size on scans.

**Comment by AllenFang** [comment]
Thanks a lot for your fast and very detail response :), you r right, we also to set batch and max result size on scan to avoid this issue, because our hbase is HBase 0.98.6 ;(  Anyway, Thanks a lot !!!

**Comment by AllenFang** [comment]
HI @housejester 
sorry, another stupid question for <a href="http://mail-archives.apache.org/mod_mbox/hbase-user/201507.mbox/%3CCAE8tVd%3Dbf4zxrWFOS7Htn291cQAHdWYiSt1%2Bg7qLa8yHeMCuAg%40mail.gmail.com%3E">RS Crash: OOME: Requested Array Size Exceeds VM Limit.</a>. Did you think this problem is really about the JDK version difference(1.6 vs 1.7)?
